package com.model;

/**
 * TBook generated by MyEclipse Persistence Tools
 */

public class TBook implements java.io.Serializable
{

	private Integer bookId;
	private String bookName;
	private String bookZuozhe;
	private String bookChubanshe;

	private String bookChubanriqi;
	private String bookIsbm;
	private String bookPrice;
	private int catelogId;
	
	private int leibieId;
	private String del;
	
	private int jieyuecishu;
	
	private TCatelog catelog;
	private TLeibie leibie;

	public Integer getBookId()
	{
		return bookId;
	}

	public void setBookId(Integer bookId)
	{
		this.bookId = bookId;
	}

	public String getBookName()
	{
		return bookName;
	}

	public void setBookName(String bookName)
	{
		this.bookName = bookName;
	}

	public String getBookZuozhe()
	{
		return bookZuozhe;
	}

	public int getLeibieId() {
		return leibieId;
	}

	public void setLeibieId(int leibieId) {
		this.leibieId = leibieId;
	}

	public TCatelog getCatelog() {
		return catelog;
	}

	public void setCatelog(TCatelog catelog) {
		this.catelog = catelog;
	}

	public TLeibie getLeibie() {
		return leibie;
	}

	public int getJieyuecishu() {
		return jieyuecishu;
	}

	public void setJieyuecishu(int jieyuecishu) {
		this.jieyuecishu = jieyuecishu;
	}

	public void setLeibie(TLeibie leibie) {
		this.leibie = leibie;
	}

	public void setBookZuozhe(String bookZuozhe)
	{
		this.bookZuozhe = bookZuozhe;
	}

	public String getBookChubanshe()
	{
		return bookChubanshe;
	}

	public void setBookChubanshe(String bookChubanshe)
	{
		this.bookChubanshe = bookChubanshe;
	}

	public String getBookChubanriqi()
	{
		return bookChubanriqi;
	}

	public void setBookChubanriqi(String bookChubanriqi)
	{
		this.bookChubanriqi = bookChubanriqi;
	}

	public String getBookIsbm()
	{
		return bookIsbm;
	}

	public void setBookIsbm(String bookIsbm)
	{
		this.bookIsbm = bookIsbm;
	}

	public String getBookPrice()
	{
		return bookPrice;
	}

	public void setBookPrice(String bookPrice)
	{
		this.bookPrice = bookPrice;
	}

	public int getCatelogId()
	{
		return catelogId;
	}

	public void setCatelogId(int catelogId)
	{
		this.catelogId = catelogId;
	}

	public String getDel()
	{
		return del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}