package com.model;

/**
 * TCatelog generated by MyEclipse Persistence Tools
 */

public class TCatelog implements java.io.Serializable
{

	private Integer catelogId;
	private String catelogName;
	private String catelogDel;

	

	public Integer getCatelogId()
	{
		return this.catelogId;
	}
	

	public String getCatelogDel()
	{
		return catelogDel;
	}

	public void setCatelogDel(String catelogDel)
	{
		this.catelogDel = catelogDel;
	}

	public void setCatelogId(Integer catelogId)
	{
		this.catelogId = catelogId;
	}

	public String getCatelogName()
	{
		return this.catelogName;
	}

	public void setCatelogName(String catelogName)
	{
		this.catelogName = catelogName;
	}

	

}