package com.model;

/**
 * TJieyue generated by MyEclipse Persistence Tools
 */

public class TJieyue implements java.io.Serializable
{

	private Integer id;
	private String userJiehao;
	private int bookId;
	private String jieyueShijian;

	private String yinghuanShijian;
	private String shifouhuan;
	private String guihuanShijian;
	private String fajin;
	
	private String beizhu;
	
	private TBook book;

	public Integer getId()
	{
		return id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getUserJiehao()
	{
		return userJiehao;
	}

	public void setUserJiehao(String userJiehao)
	{
		this.userJiehao = userJiehao;
	}

	public int getBookId()
	{
		return bookId;
	}

	public String getShifouhuan()
	{
		return shifouhuan;
	}

	public void setShifouhuan(String shifouhuan)
	{
		this.shifouhuan = shifouhuan;
	}

	public void setBookId(int bookId)
	{
		this.bookId = bookId;
	}

	public String getJieyueShijian()
	{
		return jieyueShijian;
	}

	public void setJieyueShijian(String jieyueShijian)
	{
		this.jieyueShijian = jieyueShijian;
	}

	public String getYinghuanShijian()
	{
		return yinghuanShijian;
	}

	public void setYinghuanShijian(String yinghuanShijian)
	{
		this.yinghuanShijian = yinghuanShijian;
	}

	public String getGuihuanShijian()
	{
		return guihuanShijian;
	}

	public void setGuihuanShijian(String guihuanShijian)
	{
		this.guihuanShijian = guihuanShijian;
	}

	

	public String getFajin()
	{
		return fajin;
	}

	public void setFajin(String fajin)
	{
		this.fajin = fajin;
	}

	public String getBeizhu()
	{
		return beizhu;
	}

	public void setBeizhu(String beizhu)
	{
		this.beizhu = beizhu;
	}

	public TBook getBook()
	{
		return book;
	}

	public void setBook(TBook book)
	{
		this.book = book;
	}
	
}